baseURL = "http://rasheddoha.github.io/"
languageCode = "en-us"
title = "An internet page"
author = "Rashed Doha"
theme = "stoic"
hasCJKLanguage = true
summaryLength=10
paginate=5
disqusShortname = "rasheddoha-github-io"
copyright = "&#169; Rashed Doha. All rights reserved."
[permalinks]
  posts= "/:year/:month/:title/"


[params]
    favicon = "circle.ico"
    [params.home]
        name = "Rashed Doha"
        profilepic = "/images/headshot.jpg"
    [[params.social]]
        icon = "twitter"
        url = "https://twitter.com/RashedDoha"
    [[params.social]]
        icon = "github"
        url = "https://github.com/RashedDoha"
    [[params.social]]
        icon = "linkedin"
        url = "https://linkedin.com/in/rasheddoha"


[menu]
    [[menu.main]]
        name = "About"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Blog"
        url = "/posts"
        weight = 2
    [[menu.main]]
        name = "News"
        url = "/news"
        weight = 3
    [[menu.main]]
        name = "Stuff"
        url = "/stuff"
        weight = 4

[outputFormats]
    [outputFormats.RSS]
        baseName = "rss"

[outputs]
    page = ["HTML"]
    home = ["HTML"]
    section = ["HTML","RSS"]
    taxonomyTerm = ["HTML"]
    taxonomy = ["HTML"]
