baseURL = "http://example.org/"
languageCode = "en-us"
title = "An internet page"
theme = "stoic"


[params]
    favicon = "circle.ico"
    [params.home]
        name = "Rashed Doha"
        profilepic = "/images/fall.JPG"
    [[params.social]]
        icon = "twitter"
        url = "https://twitter.com/RashedDoha"
    [[params.social]]
        icon = "github"
        url = "https://github.com/RashedDoha"
    [[params.social]]
        icon = "linkedin"
        url = "https://linkedin.com/in/rasheddoha"


[menu]
    [[menu.main]]
        name = "About"
        url = "#about"
        weight = 1
    [[menu.main]]
        name = "Blog"
        url = "#blog"
        weight = 2
    [[menu.main]]
        name = "Publications"
        url = "#publications"
        weight = 3
    [[menu.main]]
        name = "News"
        url = "#news"
        weight = 4
    [[menu.main]]
        name = "Stuff"
        url = "#stuff"
        weight = 5
